[workspace]
authors = ["Neppel Elian <elian.neppel@posteo.eu>"]
channels = ["conda-forge"]
name = "asyncio-gazebo"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64",]
version = "1.0.0"

[tasks]
example = "python3 -m asyncio_gazebo.example"
test = "pytest ./tests -s -vv"

[dependencies]
gz-jetty = ">=1.0.0,<2"
python = ">=3.10.0,<3.14"
gz-transport = ">=15.0.2,<16"
gz-transport-python = ">=15.0.2,<16"
pytest = "*"
pytest-asyncio = "*"
uv = "*"

[pypi-dependencies]
asyncio-gazebo = {path=".", editable=true}

[environments]
py310 = {features = ["py310"]}
py311 = {features = ["py311"]}
py312 = {features = ["py312"]}
py313 = {features = ["py313"]}
# py314 = {features = ["py314"]} # gazebo not compatible

[feature.py310]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64",]
dependencies = {python = "3.10.*"}

[feature.py311]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64",]
dependencies = {python = "3.11.*"}

[feature.py312]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64",]
dependencies = {python = "3.12.*"}

[feature.py313]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64",]
dependencies = {python = "3.13.*"}

# [feature.py314.dependencies]
# python = "==3.14"
